# pvc-pod-demo.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard-rwo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:3.2-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: "/data"
            name: redis-vol
      volumes:
         - name: redis-vol
           persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
spec:
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyapp
        image: dab8106/flaskapp:10122022
        env:
          - name: FLASK_APP
            value: app.py
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pyapp-svc
spec:
  type: LoadBalancer
  selector:
    app: pyapp
  ports:
  - port: 80
    targetPort: 5000